"""cookie_manager.py - Robust cookie handling for Douyin HD Downloader.

Replaces fragile ``--cookies-from-browser`` DPAPI decryption with a portable
Netscape-format ``cookies.txt`` workflow. The priority order is:

  1. An explicit ``cookies.txt`` file (imported or dropped next to the app).
  2. Live extraction from an installed browser via Playwright (no DPAPI).
  3. No cookies (anonymous access — works for many public videos).

The Playwright extraction opens a real browser window, lets the user log in to
Douyin, then reads cookies via ``context.storage_state()``. This never touches
the on-disk Chromium cookie DB, so it is immune to the DPAPI decrypt failures
described in https://github.com/yt-dlp/yt-dlp/issues/10927.
"""

from __future__ import annotations

import os
import pathlib
import time
from typing import Dict, List, Optional

# Netscape cookies.txt header line yt-dlp expects.
NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by Douyin HD Downloader\n\n"

# Cookies that indicate a usable Douyin anonymous/login session.
DOUYIN_REQUIRED_KEYS = {"ttwid", "odin_tt", "passport_csrf_token"}

# Playwright browser channel map. Chromium-family browsers use the "chromium"
# engine with a specific channel; Firefox uses its own engine.
BROWSER_CHANNELS = {
    "Brave": ("chromium", "brave"),
    "Chrome": ("chromium", "chrome"),
    "Edge": ("chromium", "msedge"),
    "Chromium": ("chromium", None),
    "Firefox": ("firefox", None),
}

DEFAULT_LOGIN_URL = "https://www.douyin.com/"


class CookieError(Exception):
    """User-facing error raised when cookie import/extraction fails."""


class CookieManager:
    """Manage the app's cookies.txt file and browser-based extraction."""

    def __init__(self, cookies_path: Optional[str] = None):
        # Where the app keeps its canonical cookies.txt.
        self._app_dir = pathlib.Path(__file__).resolve().parent
        self.cookies_path: Optional[str] = cookies_path or self._find_local_cookies()

    # ------------------------------------------------------------------ #
    # Discovery
    # ------------------------------------------------------------------ #

    def _find_local_cookies(self) -> Optional[str]:
        """Return a cookies.txt in the CWD or app folder if one exists."""
        for cand in (
            pathlib.Path.cwd() / "cookies.txt",
            self._app_dir / "cookies.txt",
        ):
            if cand.is_file():
                return str(cand)
        return None

    def default_cookies_path(self) -> str:
        """Canonical path the app writes extracted cookies to."""
        return str(self._app_dir / "cookies.txt")

    def get_cookie_source(self) -> str:
        """Return ``"file"`` if a cookies.txt is active, else ``"none"``."""
        if self.cookies_path and os.path.isfile(self.cookies_path):
            return "file"
        return "none"

    def get_cookies_for_yt_dlp(self) -> Optional[str]:
        """Return the cookies.txt path yt-dlp should use, or ``None``."""
        if self.cookies_path and os.path.isfile(self.cookies_path):
            return self.cookies_path
        return None

    # ------------------------------------------------------------------ #
    # Import (file)
    # ------------------------------------------------------------------ #

    def set_cookies_file(self, path: str) -> None:
        """Adopt an existing cookies.txt selected by the user."""
        if not path or not os.path.isfile(path):
            raise CookieError(f"Cookies file not found: {path}")
        self.cookies_path = path

    def clear_cookies(self) -> None:
        """Forget the active cookies.txt (does not delete the file)."""
        self.cookies_path = None

    # ------------------------------------------------------------------ #
    # Extraction (browser via Playwright — no DPAPI)
    # ------------------------------------------------------------------ #

    def extract_cookies_from_browser(
        self,
        browser: str = "Chrome",
        *,
        login_url: str = DEFAULT_LOGIN_URL,
        timeout: int = 300,
        headless: bool = False,
        on_status=None,
    ) -> str:
        """Open a browser, let the user log in, then save cookies.txt.

        Returns the path to the written cookies.txt. Raises :class:`CookieError`
        on failure. This deliberately avoids reading the browser's on-disk
        cookie DB (the source of DPAPI errors); instead it drives a fresh
        Playwright browser and reads cookies from its live context.
        """
        engine, channel = BROWSER_CHANNELS.get(browser, ("chromium", None))
        self._report(on_status, f"Launching {browser} for cookie login…")

        try:
            from playwright.sync_api import sync_playwright
        except ImportError as exc:
            raise CookieError(
                "Playwright is not installed. Run: pip install playwright "
                "&& playwright install chromium"
            ) from exc

        cookies: List[dict] = []
        try:
            with sync_playwright() as p:
                launcher = getattr(p, engine)
                launch_kwargs: dict = {"headless": headless}
                if channel:
                    launch_kwargs["channel"] = channel
                try:
                    browser_obj = launcher.launch(**launch_kwargs)
                except Exception:
                    # Channel not installed — fall back to bundled engine.
                    browser_obj = launcher.launch(headless=headless)

                context = browser_obj.new_context(locale="zh-CN")
                page = context.new_page()
                try:
                    page.goto(login_url, wait_until="domcontentloaded",
                              timeout=60_000)
                except Exception:
                    pass

                self._report(
                    on_status,
                    "Log in to Douyin in the opened window. Cookies are "
                    "captured automatically once required cookies appear.",
                )

                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    try:
                        cookies = context.cookies()
                    except Exception:
                        cookies = []
                    names = {c.get("name") for c in cookies}
                    if DOUYIN_REQUIRED_KEYS.issubset(names):
                        break
                    try:
                        page.wait_for_timeout(1000)
                    except Exception:
                        break

                # Final read in case the loop exited on timeout.
                try:
                    cookies = context.cookies()
                except Exception:
                    pass
                context.close()
                browser_obj.close()
        except CookieError:
            raise
        except Exception as exc:
            raise CookieError(f"Browser cookie extraction failed: {exc}") from exc

        if not cookies:
            raise CookieError(
                "No cookies were captured. Make sure you completed login "
                "before the window closed."
            )

        out_path = self.default_cookies_path()
        self._write_netscape(cookies, out_path)
        self.cookies_path = out_path
        self._report(on_status, f"Saved {len(cookies)} cookies to cookies.txt")
        return out_path

    def refresh_cookies(self, browser: str = "Chrome", **kwargs) -> str:
        """Re-run extraction for *browser* (alias for :meth:`extract...`)."""
        return self.extract_cookies_from_browser(browser, **kwargs)

    # ------------------------------------------------------------------ #
    # Netscape cookies.txt serialization
    # ------------------------------------------------------------------ #

    @staticmethod
    def _write_netscape(cookies: List[dict], path: str) -> None:
        """Write Playwright cookie dicts as a Netscape cookies.txt file."""
        lines = [NETSCAPE_HEADER]
        for c in cookies:
            domain = c.get("domain", "")
            if not domain:
                continue
            # Netscape format: domain, include_subdomains, path, secure,
            # expires, name, value  (tab-separated).
            include_sub = "TRUE" if domain.startswith(".") else "FALSE"
            path_val = c.get("path", "/") or "/"
            secure = "TRUE" if c.get("secure") else "FALSE"
            expires = int(c.get("expires") or 0)
            if expires <= 0:
                # Session cookie — yt-dlp accepts 0 as "no expiry stored".
                expires = 0
            name = c.get("name", "")
            value = c.get("value", "")
            if not name:
                continue
            lines.append(
                f"{domain}\t{include_sub}\t{path_val}\t{secure}\t"
                f"{expires}\t{name}\t{value}\n"
            )
        pathlib.Path(path).write_text("".join(lines), encoding="utf-8")

    @staticmethod
    def parse_netscape(path: str) -> Dict[str, str]:
        """Read a Netscape cookies.txt into a ``{name: value}`` dict."""
        result: Dict[str, str] = {}
        try:
            for raw in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) >= 7:
                    result[parts[5]] = parts[6]
        except OSError:
            pass
        return result

    def validate_douyin_cookies(self, path: Optional[str] = None) -> bool:
        """Return True if the cookies.txt has the required Douyin keys."""
        path = path or self.cookies_path
        if not path or not os.path.isfile(path):
            return False
        cookies = self.parse_netscape(path)
        return DOUYIN_REQUIRED_KEYS.issubset(cookies.keys())

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _report(callback, message: str) -> None:
        if callback:
            callback(message)
